version: 2
registries:
  spring-milestones:
    type: maven-repository
    url: https://repo.spring.io/milestone
updates:
  - package-ecosystem: gradle
    target-branch: main
    directory: /
    schedule:
      interval: daily
      time: '03:00'
      timezone: Etc/UTC
    labels:
      - 'type: dependency-upgrade'
    registries:
      - spring-milestones
    ignore:
      - dependency-name: org.junit:junit-bom
        update-types:
          - version-update:semver-major
      - dependency-name: org.mockito:mockito-bom
        update-types:
          - version-update:semver-major
      - dependency-name: com.gradle.develocity
        update-types:
          - version-update:semver-major
          - version-update:semver-minor
      - dependency-name: io.spring.ge.conventions
        update-types:
          - version-update:semver-major
          - version-update:semver-minor
      - dependency-name: '*'
        update-types:
          - version-update:semver-major
          - version-update:semver-minor
  - package-ecosystem: github-actions
    target-branch: main
    directory: /
    schedule:
      interval: weekly
    labels:
      - 'type: task'
      - 'in: build'
    ignore:
      - dependency-name: sjohnr/*
  - package-ecosystem: npm
    target-branch: main
    directory: /docs
    schedule:
      interval: weekly

  - package-ecosystem: npm
    target-branch: docs-build
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    target-branch: docs-build
    directory: /
    schedule:
      interval: weekly
    labels:
      - 'type: task'
      - 'in: build'
    ignore:
      - dependency-name: sjohnr/*