antora:
  extensions:
  - require: '@springio/antora-extensions'
    root_component_name: 'kerberos'
site:
  title: Spring Security Kerberos
  url: https://docs.spring.io/spring-security-kerberos/reference
  robots: allow
git:
  ensure_git_suffix: false
content:
  sources:
  - url: https://github.com/spring-projects/spring-security-kerberos
    # Refname matching:
    # https://docs.antora.org/antora/latest/playbook/content-refname-matching/
    branches: [main,'*.x','!1.*.x']
    tags: ['*','!1.*']
    start_path: spring-security-kerberos-docs
asciidoc:
  extensions:
    - '@asciidoctor/tabs'
    - '@springio/asciidoctor-extensions'
    - '@springio/asciidoctor-extensions/include-code-extension'
  attributes:
    page-stackoverflow-url: https://stackoverflow.com/tags/spring-security
    page-related-doc-categories: security
    page-related-doc-projects: framework,graphql
    hide-uri-scheme: '@'
    tabs-sync-option: '@'
urls:
  latest_version_segment_strategy: redirect:to
  latest_version_segment: ''
  redirect_facility: httpd
runtime:
  log:
    failure_level: warn
ui:
  bundle:
    url: https://github.com/spring-io/antora-ui-spring/releases/download/v0.4.15/ui-bundle.zip
    snapshot: true
