antora:
  extensions:
    - '@antora/collector-extension'
site:
  title: Spring Security Kerberos
  url: https://spring-projects.github.io/spring-security-kerberos
  start_page: spring-security-kerberos::index.adoc
asciidoc:
  attributes:
    page-pagination: true
content:
  sources:
    - url: ..
      start_path: spring-security-kerberos-docs
urls:
  latest_version_segment_strategy: redirect:to
  latest_version_segment: ''
  redirect_facility: static
ui:
  bundle:
    url: https://github.com/spring-io/antora-ui-spring/releases/download/latest/ui-bundle.zip
    snapshot: true
