server:
    port: 8080
app:
    ad-domain: example.org
    ad-server: ldap://vagrantvm.example.org
    service-principal: HTTP/cypher.example.org@EXAMPLE.ORG
    keytab-location: /tmp/tomcat.keytab
    ldap-search-base: dc=example,dc=org
    ldap-search-filter: "(| (userPrincipalName={0}) (sAMAccountName={0}))"
