name: CI

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '.github/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - nickname: linux jdk17
            java: 17
    name: CI Build ${{ matrix.nickname }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: ${{ matrix.java }}
          cache: gradle
      - name: Build
        run: ./gradlew build
      - uses: actions/upload-artifact@v3
        if: ${{ failure() }}
        with:
          name: buildreports
          retention-days: 1
          path: |
            */build/reports
            spring-security-kerberos-samples/*/build/reports
