name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'spring-projects/spring-security-kerberos' }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - nickname: linux adopt 17
            version: 17
            distribution: adopt
          - nickname: linux liberica 17
            version: 17
            distribution: liberica
    name: CI Build ${{ matrix.nickname }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: ${{ matrix.distribution }}
          java-version: ${{ matrix.version }}
      - name: Build
        env:
          GRADLE_ENTERPRISE_CACHE_USERNAME: ${{ secrets.GRADLE_ENTERPRISE_CACHE_USER }}
          GRADLE_ENTERPRISE_CACHE_PASSWORD: ${{ secrets.GRADLE_ENTERPRISE_CACHE_PASSWORD }}
          GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GRADLE_ENTERPRISE_SECRET_ACCESS_KEY }}
        run: ./gradlew build
      - uses: actions/upload-artifact@v3
        if: ${{ failure() }}
        with:
          name: buildreports
          retention-days: 1
          path: |
            */build/reports
            spring-security-kerberos-samples/*/build/reports
  publish:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: 17
      - name: Build
        env:
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.GPG_PRIVATE_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.GPG_PASSPHRASE }}
          ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
          ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
          GRADLE_ENTERPRISE_CACHE_USERNAME: ${{ secrets.GRADLE_ENTERPRISE_CACHE_USER }}
          GRADLE_ENTERPRISE_CACHE_PASSWORD: ${{ secrets.GRADLE_ENTERPRISE_CACHE_PASSWORD }}
          GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GRADLE_ENTERPRISE_SECRET_ACCESS_KEY }}
        run: |
          ./gradlew build publishArtifacts \
            -PartifactoryUsername="$ARTIFACTORY_USERNAME" \
            -PartifactoryPassword="$ARTIFACTORY_PASSWORD"
  docs:
    runs-on: ubuntu-latest
    needs: [publish]
    steps:
      - uses: actions/checkout@v3
      - name: Dispatch (partial build)
        if: github.ref_type == 'branch'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh workflow run deploy-docs.yml -r docs-build -f build-refname=${{ github.ref_name }}
