name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - '**'

jobs:
  build:
    name: Build
    uses: spring-io/spring-security-release-tools/.github/workflows/build.yml@v1
    strategy:
      matrix:
        include:
        - nickname: linux adopt 17
          jdk: 17
          jdk-distribution: adopt
        - nickname: linux liberica 17
          jdk: 17
          jdk-distribution: liberica
    with:
      runs-on: ubuntu-latest
      java-version: ${{ matrix.jdk }}
      distribution: ${{ matrix.jdk-distribution }}
    secrets: inherit
  deploy-artifacts:
    name: Deploy Artifacts
    needs: [ build ]
    uses: spring-io/spring-security-release-tools/.github/workflows/deploy-artifacts.yml@v1
    with:
      should-deploy-artifacts: ${{ needs.build.outputs.should-deploy-artifacts }}
    secrets: inherit
  deploy-javadocs:
    name: Deploy Javadocs
    needs: [ build ]
    uses: spring-io/spring-security-release-tools/.github/workflows/deploy-docs.yml@v1
    with:
      should-deploy-docs: ${{ needs.build.outputs.should-deploy-artifacts }}
    secrets: inherit
  antora:
    name: Invoke Antora Docs Build
    runs-on: ubuntu-latest
    needs: [build]
    if: ${{ needs.build.outputs.should-deploy-artifacts == 'true' }}
    steps:
      - uses: actions/checkout@v4
      - name: Dispatch (partial build)
        if: github.ref_type == 'branch'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh workflow run deploy-docs.yml -r docs-build -f build-refname=${{ github.ref_name }}
