name: Rebuild Search Index
on:
  workflow_dispatch:
permissions:
  actions: write
jobs:
  build:
    if: github.repository_owner == 'spring-projects'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: docs-build
        fetch-depth: 1
    - name: Dispatch
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: gh workflow run rebuild-search-index.yml -r $(git rev-parse --abbrev-ref HEAD)

